# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.

name: DEPLOY_MAPPING_TASK
 
# Controls when the workflow will run
on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      committed_sha:
        description: "Hash to deploy"
        type: string
        required: true
      repo_name:
        description: "Repository Name (owner/repo)"
        type: string
        required: true
        default: "owner/repo"
      resource_type:
        description: "IICS Resource Type (MTT=Mapping Task, DSS=Sync Task)"
        type: string
        required: true
        default: "MTT"

env:
  IICS_LOGIN_URL: https://dm-em.informaticacloud.com
  IICS_POD_URL: https://emw1.dm-em.informaticacloud.com/saas
  
  # This is overriding until we connect the repository with a workflow_dispatch

  COMMIT_HASH: ${{ github.event.inputs.committed_sha || github.sha }}
  REPO_NAME: ${{ github.event.inputs.repo_name || github.repository }}
  RESOURCE_TYPE: ${{ github.event.inputs.resource_type || 'MTT' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dev_build:
    name: Review Development Code
    environment:
      name: IICS_USERNAME
    env:
      IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
      IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'deploy') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install python and dependent modules
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Install python modules
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Login to development
        run: |
            python ./scripts/iics_auth.py

      - name: Test Committed Mapping Tasks
        if: ${{ false }}
        run: python ./scripts/deploy_dev.py

  uat_commit:
    name: Complete uat promotion
    environment:
      name: uat
    if: ${{ github.event_name == 'workflow_dispatch' }}
    env:
      UAT_IICS_USERNAME: ${{ secrets.UAT_IICS_USERNAME }}
      UAT_IICS_PASSWORD: ${{ secrets.UAT_IICS_PASSWORD }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    needs: dev_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_NAME }}
          ref: dev2
          token: ${{ secrets.GH_TOKEN }}
          path: iics # Clones the iicsrepo repository into the iicsrepo directory

      - uses: actions/checkout@v3
        with:
          path: IICS_CICD_PIPELINE

      # Install python and dependent modules
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Install python modules
        run: |
            python -m pip install --upgrade pip
            pip install -r IICS_CICD_PIPELINE/requirements.txt

      - name: Set default username
        run: git config --global user.email "github-actions[bot]@users.noreply.github.com"; git config --global user.name "github-actions[bot]"

      - name: Commit changes to UAT
        run: cd ./iics && git fetch --all && (git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH} || { git checkout --theirs . && git add . && git cherry-pick --continue; }) && git pull && git push

      - name: Get latest UAT commit hash
        run: cd ./iics; git pull; echo "UAT_COMMIT_HASH=$(git log -1 --pretty=format:%H)" >> $GITHUB_ENV
          
      - name: get the folder path and the contain
        run: pwd
          
      - name: Login to UAT
        run: python ./IICS_CICD_PIPELINE/scripts/iics_auth.py

      - name: Sync and test UAT deployment
        run: python ./IICS_CICD_PIPELINE/scripts/deploy_uat.py
